import PageHero from "../components/PageHero";
import SiteFooter from "../components/SiteFooter";

export default function ServeurPage() {
  return <main><PageHero eyebrow="L'UNIVERS COBBLESTAR" title="Explore à ton rythme." accent="Construis ton histoire." description="Minecraft et Cobblemon réunis dans une aventure communautaire accessible, vivante et pensée pour durer." />
    <section className="content-section"><div className="feature-grid"><article className="feature-card featured"><div className="feature-number">01</div><div className="feature-icon pink">◉</div><h3>Capture & collection</h3><p>Compose ton équipe de Cobblemon et complète ta collection à travers les différents biomes.</p><span className="card-line" /></article><article className="feature-card"><div className="feature-number">02</div><div className="feature-icon cyan">⌁</div><h3>Exploration enrichie</h3><p>Un modpack Fabric 1.21.1 soigneusement construit pour enrichir l’aventure sans la dénaturer.</p><span className="card-line" /></article><article className="feature-card"><div className="feature-number">03</div><div className="feature-icon yellow">✦</div><h3>Communauté</h3><p>Échanges, combats amicaux et événements : avance à ton rythme, mais jamais vraiment seul.</p><span className="card-line" /></article></div>
      <section className="server-scenery"><div className="server-scenery-head"><div><span className="kicker">APERÇU DE COBBLEMON</span><h2>Le monde continue<br /><em>au-delà du spawn.</em></h2></div><p>Quelques scènes issues de la galerie officielle du mod. Le contenu exact de CobbleStar évoluera avec son propre modpack.</p></div><div className="server-scenery-grid"><figure className="scenery-large"><img src="/cobblemon-lakeside.webp" alt="Cobblemon caché près d’un lac" /><figcaption>Rencontres sauvages <span>01</span></figcaption></figure><figure><img src="/cobblemon-shop.webp" alt="Intérieur animé dans Cobblemon" /><figcaption>Lieux vivants <span>02</span></figcaption></figure><figure><img src="/cobblemon-berries.webp" alt="Champ de baies dans Cobblemon" /><figcaption>Culture & collection <span>03</span></figcaption></figure></div><a className="showcase-source" href="https://cobblemon.com/en" target="_blank" rel="noreferrer">Images officielles Cobblemon ↗</a></section>
      <div className="info-banner"><div><span className="status-dot" /><small>ADRESSE DU SERVEUR</small><strong>23.109.138.130:25574</strong></div><div><small>VERSION</small><strong>Minecraft 1.21.1 • Fabric</strong></div><a className="button button-primary" href="/telecharger">Installer le launcher</a></div>
    </section><SiteFooter /></main>;
}
