"use client";
import { useState } from 'react';
import type { StudioContent, StudioQuest } from '../../../api/src/quest-studio-schema';
import { storyEvents, type StoryCatalog, type StoryEvent } from '../../../api/src/quest-events';
import s from './studio.module.css';

type Choice = {id:string;label:string};
type Objective = StudioQuest['objectives'][number];
export const blankObjective = (event: StoryEvent): Objective => ({source:event.id,label:event.title,target:1,unique:event.unique ?? false,optional:false,alternativeGroup:'',filters:{}});
export const eventTitle = (id:string) => storyEvents.find(e => e.id === id)?.title ?? 'Ancien événement à reconfigurer';

export function ResourcePicker({label,value,choices,onChange,required=false}: {label:string;value:string;choices:Choice[];onChange:(value:string)=>void;required?:boolean}) {
  const [search,setSearch] = useState('');
  const current = choices.find(c => c.id === value);
  const results = choices.filter(c => c.id === value || c.label.toLocaleLowerCase().includes(search.toLocaleLowerCase())).slice(0,120);
  if (current && !results.some(c => c.id === current.id)) results.unshift(current);
  return <div className={s.picker}><label>{label}<input aria-label={`Rechercher · ${label}`} placeholder="Rechercher par nom…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}><option value="">{required ? 'Choisir…' : 'Sans restriction'}</option>{value && !current && <option value={value}>Sélection existante · catalogue indisponible</option>}{results.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label>{!choices.length && <small>La liste sera disponible après synchronisation du serveur.</small>}{results.length >= 120 && <small>Affine la recherche pour voir les autres résultats.</small>}</div>;
}

export function StoryEditor({quest,content,catalog,onChange,onContent,onDuplicate}: {quest:StudioQuest;content:StudioContent;catalog:StoryCatalog|null;onChange:(q:StudioQuest)=>void;onContent:(d:StudioContent)=>void;onDuplicate:()=>void}) {
  const [tab,setTab] = useState('parcours'), [step,setStep] = useState(0), [search,setSearch] = useState(''), [group,setGroup] = useState('Tous');
  const [simulation,setSimulation] = useState<number|null>(null);
  const o = quest.objectives[step];
  const event = storyEvents.find(e=>e.id===o?.source);
  const npcChoices = content.npcs.filter(n=>n.enabled).map(n=>({id:n.id,label:n.name}));
  const givers = content.npcs.filter(n=>n.questIds.includes(quest.id));
  const issues = quest.objectives.flatMap((o,i) => {
    const e=storyEvents.find(e=>e.id===o.source);
    if (!e) return [`Étape ${i+1} : choisis un nouvel événement.`];
    const errors=e.fields.filter(f=>f.required && !o.filters[f.key]).map(f=>`Étape ${i+1} : ${f.label}`);
    if(o.source==='minecraft_visit' && !o.filters.biome && !o.filters.dimension) errors.push(`Étape ${i+1} : choisis le lieu à explorer.`);
    if(o.source==='story_npc_talk' && !npcChoices.some(n=>n.id===o.filters.npc)) errors.push(`Étape ${i+1} : personnage absent ou en pause.`);
    return errors;
  });
  if (!quest.autoStart && !givers.length) issues.push('Choisis le personnage qui propose la quête, dans Introduction.');
  function patch(values:Partial<StudioQuest>){onChange({...quest,...values});}
  function patchStep(values:Partial<Objective>){patch({objectives:quest.objectives.map((v,i)=>i===step?{...v,...values}:v)});}
  function filter(key:string,value:string){const filters={...o.filters};if(value)filters[key]=value;else delete filters[key];patchStep({filters});}
  function add(e:StoryEvent){patch({objectives:[...quest.objectives,blankObjective(e)]});setStep(quest.objectives.length);setSimulation(null);}
  function move(direction:number){const target=step+direction;if(target<0||target>=quest.objectives.length)return;const objectives=[...quest.objectives];[objectives[step],objectives[target]]=[objectives[target],objectives[step]];patch({objectives});setStep(target);setSimulation(null);}
  const titles = {intro:'Introduction',parcours:'Scénario',rewards:'Récompenses',review:'Relecture'};
  return <>
    <div className={s.sectionTitle}><div><span className={s.eyebrow}>L’ATELIER DES HISTOIRES</span><h2>{quest.title}</h2></div><button onClick={onDuplicate}>Dupliquer l’histoire</button></div>
    <nav className={s.storyTabs} aria-label="Écriture du scénario">{Object.entries(titles).map(([id,title],i)=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}><span>{i+1}</span>{title}{id==='review' && issues.length>0?` (${issues.length})`:''}</button>)}</nav>
    {tab==='intro' && <section className={s.storySection}><h3>De quoi parle cette aventure ?</h3><label>Titre de l’histoire<input value={quest.title} onChange={e=>patch({title:e.target.value})}/></label><label>Le pitch · ce que le joueur découvrira<textarea aria-label="Le pitch · ce que le joueur découvrira" value={quest.description} onChange={e=>patch({description:e.target.value})} placeholder="Une étrange lueur inquiète les habitants d’Asteria et de Nébélia…"/></label><div className={s.grid}><label>Place dans l’univers<select aria-label="Place dans l’univers" value={quest.kind} onChange={e=>patch({kind:e.target.value as StudioQuest['kind']})}><option value="STORY">Histoire principale</option><option value="SIDE">Aventure secondaire</option></select></label><label>Difficulté<select aria-label="Difficulté" value={quest.difficulty} onChange={e=>patch({difficulty:e.target.value as StudioQuest['difficulty']})}>{[['FACILE','Découverte'],['NORMAL','Accessible'],['DIFFICILE','Un défi'],['EXPERT','Pour les experts']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><h3>Comment l’histoire commence-t-elle ?</h3><label>Déclenchement<select aria-label="Déclenchement" value={quest.autoStart?'auto':'npc'} onChange={e=>patch({autoStart:e.target.value==='auto'})}><option value="npc">Le joueur accepte auprès d’un personnage</option><option value="auto">Dès que les prérequis sont remplis</option></select></label>{!quest.autoStart && <div className={s.checks}>{npcChoices.length===0?<p>Crée d’abord un personnage dans l’onglet Personnages.</p>:npcChoices.map(n=><label key={n.id}><input type="checkbox" checked={givers.some(g=>g.id===n.id)} onChange={e=>{const d=structuredClone(content);const npc=d.npcs.find(v=>v.id===n.id)!;npc.questIds=e.target.checked?[...new Set([...npc.questIds,quest.id])]:npc.questIds.filter(id=>id!==quest.id);if(e.target.checked&&npc.role==='DIALOGUE_ONLY')npc.role='DIALOGUE_QUEST';onContent(d);}}/>{n.label}</label>)}</div>}<h3>À terminer avant de commencer</h3><div className={s.checks}>{content.questConfig.quests.filter(q=>q.id!==quest.id).map(q=><label key={q.id}><input type="checkbox" checked={quest.requires.includes(q.id)} onChange={e=>patch({requires:e.target.checked?[...quest.requires,q.id]:quest.requires.filter(id=>id!==q.id)})}/>{q.title}</label>)}{content.questConfig.quests.length<2&&<p>Aucun prérequis nécessaire pour ta première histoire.</p>}</div><button className={s.primary} onClick={()=>setTab('parcours')}>Écrire le scénario →</button></section>}
    {tab==='parcours' && <>
      <div className={s.flowHeading}><div><h3>Le chemin du joueur</h3><p>Une carte = une action à vivre. Clique sur une étape pour l’écrire.</p></div><label>Déroulement<select aria-label="Déroulement" value={quest.sequential?'ordered':'parallel'} onChange={e=>{if(confirm('Changer le déroulement ? Une histoire déjà commencée doit être dupliquée avant ce changement.'))patch({sequential:e.target.value==='ordered'});}}><option value="ordered">Dans l’ordre du scénario</option><option value="parallel">Objectifs en liberté</option></select></label></div>
      {!quest.sequential&&<p className={s.hint}>Cette histoire utilise des objectifs en parallèle. Choisis « Dans l’ordre du scénario » pour créer une suite d’étapes.</p>}
      <div className={s.storyBoard}><aside className={s.timeline} aria-label="Étapes du scénario"><div className={s.bookend}><small>DÉPART</small><b>{quest.autoStart?'L’aventure commence':givers.map(n=>n.name).join(', ')||'Personnage à choisir'}</b></div>{quest.objectives.map((v,i)=><button key={i} className={s.scene} aria-pressed={step===i} onClick={()=>{setStep(i);setSimulation(null);}}><span className={s.sceneNumber}>{String(i+1).padStart(2,'0')}</span><span><small>{eventTitle(v.source)}</small><b>{v.label}</b><small>{v.target} à accomplir{v.optional?' · facultatif':''}{v.alternativeGroup?' · autre chemin possible':''}</small></span></button>)}<div className={s.bookend}><small>DÉNOUEMENT</small><b>{quest.rewards.length?`${quest.rewards.length} récompense(s)`:'La fin de ton histoire'}</b><button onClick={()=>setTab('rewards')}>Composer les récompenses</button></div></aside>
      <section className={s.inspector} aria-label="Éditeur de l’étape">{o&&<><span className={s.eyebrow}>SCÈNE {step+1} / {quest.objectives.length}</span><h3>{event?.title??'Choisir un événement'}</h3><p>{event?.description}</p><label>Consigne affichée au joueur<input value={o.label} maxLength={160} onChange={e=>patchStep({label:e.target.value})} placeholder="Pars à la rencontre du professeur…"/></label><label>Action à accomplir<select aria-label="Action à accomplir" value={o.source} onChange={e=>{const next=storyEvents.find(v=>v.id===e.target.value)!;patchStep(blankObjective(next));}}>{!event&&<option value={o.source}>Ancien événement · à remplacer</option>}{storyEvents.map(e=><option value={e.id} key={e.id}>{e.title}</option>)}</select></label><div className={s.grid}>{event?.fields.map(f=>f.kind==='number'?<label key={f.key}>{f.label}<input type="number" min={1} max={100} value={o.filters[f.key]??''} onChange={e=>filter(f.key,e.target.value)}/></label>:f.kind==='boolean'?<label key={f.key}>{f.label}<select value={o.filters[f.key]??''} onChange={e=>filter(f.key,e.target.value)}><option value="">Peu importe</option><option value="true">Oui</option><option value="false">Non</option></select></label>:<ResourcePicker key={f.key} label={f.label} value={o.filters[f.key]??''} required={f.required} choices={f.kind==='npcs'?npcChoices:catalog?.[f.kind]??[]} onChange={v=>filter(f.key,v)}/>)}</div><label>Combien de fois ?<input type="number" min={1} max={1000000} value={o.target} onChange={e=>patchStep({target:Math.max(1,+e.target.value)})}/></label><div className={s.checks}><label><input type="checkbox" checked={o.optional} onChange={e=>patchStep({optional:e.target.checked})}/> Étape bonus · ne bloque pas la suite</label></div>{o.alternativeGroup&&<p className={s.hint}>Une autre étape peut remplacer celle-ci dans cette ancienne histoire. Cette règle est conservée.</p>}<div className={s.stepActions}><button disabled={step===0} onClick={()=>move(-1)}>↑ Monter</button><button disabled={step===quest.objectives.length-1} onClick={()=>move(1)}>↓ Descendre</button><button disabled={quest.objectives.length>=24} onClick={()=>{const objectives=[...quest.objectives];objectives.splice(step+1,0,structuredClone(o));patch({objectives});setStep(step+1);}}>Dupliquer</button><button disabled={quest.objectives.length<=1} onClick={()=>{if(confirm('Retirer cette étape du brouillon ?')){patch({objectives:quest.objectives.filter((_,i)=>i!==step)});setStep(Math.max(0,step-1));}}}>Retirer</button></div></>}</section></div>
      <section className={s.eventLibrary}><div className={s.sectionTitle}><div><span className={s.eyebrow}>BOÎTE À IDÉES · {storyEvents.length} ACTIONS CONNECTÉES</span><h3>Que se passe-t-il ensuite ?</h3></div><input aria-label="Rechercher un événement" placeholder="Capturer, pêcher, parler…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className={s.chips}>{['Tous',...new Set(storyEvents.map(e=>e.group))].map(g=><button key={g} aria-pressed={group===g} onClick={()=>setGroup(g)}>{g}</button>)}</div><div className={s.events}>{storyEvents.filter(e=>(group==='Tous'||e.group===group)&&e.title.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(e=><button key={e.id} disabled={quest.objectives.length>=24} onClick={()=>add(e)}><small>{e.group}</small><b>+ {e.title}</b><span>{e.description}</span></button>)}</div><small>24 étapes maximum par histoire. Pour une grande aventure, relie plusieurs histoires avec les prérequis.</small></section>
    </>}
    {tab==='rewards'&&<section className={s.storySection}><h3>Ce que le joueur gagne</h3><p>Choisis un objet du serveur et une quantité, ou de l’expérience. Aucune commande à écrire.</p>{quest.rewards.map((r,i)=><RewardEditor key={`${quest.id}:${i}`} reward={r} catalog={catalog} onChange={r=>patch({rewards:quest.rewards.map((v,j)=>i===j?r:v)})} onRemove={()=>patch({rewards:quest.rewards.filter((_,j)=>j!==i)})}/>)}<button className={s.primary} disabled={quest.rewards.length>=20} onClick={()=>patch({rewards:[...quest.rewards,{label:'Récompense',icon:'minecraft:experience_bottle',choice:false,commands:['experience add {player} 100 points']}]})}>+ Ajouter une récompense</button></section>}
    {tab==='review'&&<section className={s.storySection}><h3>Relis l’aventure comme un joueur</h3>{issues.length?<div className={s.notice}><b>À compléter avant publication</b><ul>{issues.map((issue,i)=><li key={i}>{issue}</li>)}</ul></div>:<p className={s.hint}>Les informations principales sont remplies. La publication vérifiera aussi les dépendances et les dialogues.</p>}<p>{quest.description||'Ajoute un pitch dans Introduction.'}</p><ol className={s.readthrough}>{quest.objectives.map((o,i)=><li key={i}><b>{o.label}</b><p>{eventTitle(o.source)} · {o.target} fois{o.optional?' · bonus':''}</p></li>)}</ol><div className={s.preview}><p>SIMULATION DE L’ORDRE · PAS UN APERÇU MINECRAFT</p>{simulation===null?<button onClick={()=>setSimulation(0)}>Tester le déroulement</button>:simulation>=quest.objectives.length?<><h3>Fin du scénario</h3><p>Le joueur peut récupérer sa récompense. Aucun joueur réel n’a été modifié.</p><button onClick={()=>setSimulation(null)}>Recommencer</button></>:<><h3>{quest.objectives[simulation].label}</h3><p>Simule l’accomplissement de cette étape pour relire la suivante.</p><button onClick={()=>setSimulation(simulation+1)}>Étape accomplie →</button><button onClick={()=>setSimulation(null)}>Arrêter</button></>}</div><p>Une histoire déjà jouée doit être dupliquée avant d’en changer les étapes. Le serveur protège les progressions existantes.</p></section>}
  </>;
}

function RewardEditor({reward:r,catalog,onChange,onRemove}:{reward:StudioQuest['rewards'][number];catalog:StoryCatalog|null;onChange:(r:StudioQuest['rewards'][number])=>void;onRemove:()=>void}) {
  const give=/^give \{player\} (\S+) (\d+)$/.exec(r.commands[0]??'');
  const xp=/^experience add \{player\} (\d+) (points|levels)$/.exec(r.commands[0]??'');
  const type=give?'item':xp?.[2]??'legacy';
  function update(kind:string,itemId:string,count:number){const item=catalog?.items.find(i=>i.id===itemId);onChange({...r,icon:kind==='item'?itemId:'minecraft:experience_bottle',commands:[kind==='item'?`give {player} ${itemId} ${Math.max(1,Math.min(64,count))}`:`experience add {player} ${Math.max(1,Math.min(99999,count))} ${kind}`],label:kind==='item'?item?.label??'Objet':kind==='levels'?'Niveaux d’expérience':'Expérience'});}
  return <article className={s.card}><div className={s.grid}><label>Type de récompense<select aria-label="Type de récompense" value={type} onChange={e=>update(e.target.value,catalog?.items[0]?.id??'minecraft:bread',1)}>{type==='legacy'&&<option value="legacy">Ancienne récompense · à reconfigurer</option>}<option value="item">Un objet</option><option value="points">Points d’expérience</option><option value="levels">Niveaux d’expérience</option></select></label><label>Nom affiché<input value={r.label} onChange={e=>onChange({...r,label:e.target.value})}/></label>{type==='item'&&<ResourcePicker label="Objet offert" required value={give?.[1]??''} choices={catalog?.items??[]} onChange={v=>{if(v)update('item',v,+(give?.[2]??1));}}/>}{type!=='legacy'&&<label>Quantité offerte<input type="number" min={1} max={type==='item'?64:99999} value={+(give?.[2]??xp?.[1]??1)} onChange={e=>update(type,give?.[1]??'',+e.target.value)}/></label>}</div>{r.commands.length>1&&<p className={s.hint}>Ancienne récompense composée : elle est conservée. Modifier son type ou sa quantité la remplace par une récompense simple.</p>}<label><input type="checkbox" checked={r.choice} onChange={e=>onChange({...r,choice:e.target.checked})}/> À choisir parmi les récompenses au choix (4 maximum)</label><button onClick={onRemove}>Retirer la récompense</button></article>;
}
