CREATE TABLE star_catalog (
 id TINYINT PRIMARY KEY, catalog_json JSON NOT NULL
);
CREATE TABLE star_models (
 species VARCHAR(100) PRIMARY KEY, draft_json JSON NOT NULL,
 published_json JSON NULL, revision INT NOT NULL DEFAULT 1,
 published_revision INT NOT NULL DEFAULT 0, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 actor_id VARCHAR(64) NOT NULL
);
CREATE TABLE star_packs (
 sha1 CHAR(40) PRIMARY KEY, pack LONGBLOB NOT NULL, species_json JSON NOT NULL,
 created_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE TABLE star_publication (
 id TINYINT PRIMARY KEY, sha1 CHAR(40) NULL
);
INSERT INTO star_publication(id,sha1) VALUES(1,NULL);
CREATE TABLE star_servers (
 server_id VARCHAR(48) PRIMARY KEY, applied_hash VARCHAR(40) NOT NULL DEFAULT '',
 ready_clients INT NOT NULL DEFAULT 0, total_clients INT NOT NULL DEFAULT 0,
 last_error VARCHAR(400) NOT NULL DEFAULT '', seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
