"use client";

import { useState } from "react";
import s from "./pokemon.module.css";
import PokemonPortrait from "./PokemonPortrait";

type Stats = Record<string, number>;
type Move = { id: string; pp: number; ppUps: number };
type Values = Record<string, string | number | boolean | Stats | Move[]>;
export type Pokemon = { uuid: string; species: string; name: string; level: number; shiny: boolean; storage: "party" | "pc"; data: Record<string, unknown>; editor?: { fingerprint: string; values: Values; stats: Stats; effectiveIvs: Stats; maxHealth: number; types: string[]; dexNumber: number; form: string } };
export type PokemonChange = { field: string; value: Values[string] };
type Props = { pokemon: Pokemon[]; writable: boolean; capable: boolean; onEdit: (pokemon: Pokemon, change: PokemonChange, fingerprint: string, description: string) => void; onLegacy: (pokemon: Pokemon) => void };
const stats = [["hp", "PV"], ["attack", "Attaque"], ["defence", "Défense"], ["special_attack", "Att. spéciale"], ["special_defence", "Déf. spéciale"], ["speed", "Vitesse"]];
const types: Record<string, string> = { normal: "Normal", fire: "Feu", water: "Eau", electric: "Électrik", grass: "Plante", ice: "Glace", fighting: "Combat", poison: "Poison", ground: "Sol", flying: "Vol", psychic: "Psy", bug: "Insecte", rock: "Roche", ghost: "Spectre", dragon: "Dragon", dark: "Ténèbres", steel: "Acier", fairy: "Fée" };
const sum = (value: Stats) => Object.values(value).reduce((a, b) => a + b, 0);
const pretty = (value: string) => value.replace(/^\w+:/, "").replaceAll("_", " ");

export default function PokemonWorkspace({ pokemon, ...props }: Props) {
  const [storage, setStorage] = useState<"party" | "pc">("party"), [search, setSearch] = useState(""), [page, setPage] = useState(1), [selected, setSelected] = useState("");
  const filtered = pokemon.filter(p => p.storage === storage && `${p.name} ${p.species} ${p.uuid}`.toLowerCase().includes(search.toLowerCase()));
  const pages = Math.max(1, Math.ceil(filtered.length / 12)), current = Math.min(page, pages);
  const target = pokemon.find(p => p.uuid === selected) ?? filtered[0];
  return <div className={s.workspace}>
    <header className={s.heading}><div><span className={s.kicker}>LABORATOIRE POKÉMON</span><h3>Une collection. Tous les détails.</h3><p>Les valeurs du serveur, une édition contrôlée.</p></div><strong>{pokemon.length}<small>Pokémon</small></strong></header>
    <div className={s.toolbar}><div className={s.switcher}>{(["party", "pc"] as const).map(key => <button key={key} aria-pressed={storage === key} onClick={() => { setStorage(key); setSelected(""); setPage(1); }}>{key === "party" ? "Équipe" : "PC"}<span>{pokemon.filter(p => p.storage === key).length}</span></button>)}</div><input aria-label="Rechercher un Pokémon" placeholder="Nom, espèce, UUID…" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }}/></div>
    <div className={s.layout}><aside className={s.roster} aria-label="Collection Pokémon">{filtered.slice((current - 1) * 12, current * 12).map(p => <button key={p.uuid} className={s.card} aria-pressed={target?.uuid === p.uuid} onClick={() => setSelected(p.uuid)}><PokemonPortrait pokemon={p} compact/><span className={s.number}>{p.editor ? `#${String(p.editor.dexNumber).padStart(3, "0")}` : "PKM"}</span><span className={s.cardName}><b>{p.name}</b><small>{pretty(p.species)} {p.shiny && "· ✦ Shiny"}</small></span><strong>{p.level}<small>NIV.</small></strong></button>)}{!filtered.length && <p>Aucun Pokémon dans cette sélection.</p>}{pages > 1 && <div className={s.pagination}><button aria-label="Pokémon précédents" disabled={current === 1} onClick={() => setPage(current - 1)}>←</button><span>{current} / {pages}</span><button aria-label="Pokémon suivants" disabled={current === pages} onClick={() => setPage(current + 1)}>→</button></div>}</aside>
      {target ? <PokemonDetails key={target.uuid} pokemon={target} {...props}/> : <section className={s.detail}><h4>La collection apparaîtra ici</h4><p>Elle sera disponible après synchronisation du joueur.</p></section>}
    </div>
  </div>;
}

function PokemonDetails({ pokemon: p, writable, capable, onEdit, onLegacy }: Omit<Props, "pokemon"> & { pokemon: Pokemon }) {
  const [baseline, setBaseline] = useState(p.editor), [draft, setDraft] = useState<Values>(p.editor ? structuredClone(p.editor.values) : {}), [tab, setTab] = useState("Statistiques"), [error, setError] = useState("");
  const stale = !!baseline && baseline.fingerprint !== p.editor?.fingerprint;
  const disabled = !writable || !capable || !baseline || stale;
  const set = (key: string, value: Values[string]) => { setError(""); setDraft(old => ({ ...old, [key]: value })); };
  const apply = (field: string, label: string, override?: Values[string]) => {
    if (disabled || !baseline) return;
    setError("");
    const value = override ?? draft[field];
    const bounds: Record<string, [number, number]> = { level: [1, 100], currentHealth: [0, baseline.maxHealth], friendship: [0, 255], experience: [0, 2_000_000], scale: [.1, 3], dmaxLevel: [0, 10] };
    if (bounds[field] && (typeof value !== "number" || !Number.isFinite(value) || value < bounds[field][0] || value > bounds[field][1] || (field !== "scale" && !Number.isInteger(value)))) { setError("Valeur numérique hors limites."); return; }
    if (["ivs", "evs", "hyperIvs"].includes(field) && Object.values(value as Stats).some(n => !Number.isInteger(n) || n < (field === "hyperIvs" ? -1 : 0) || n > (field === "evs" ? 252 : 31))) { setError("Vérifie les six statistiques : aucune valeur vide, décimale ou hors limites."); return; }
    if (field === "moves" && ((value as Move[]).some(m => !/^[a-z0-9_:-]+$/.test(m.id) || !Number.isInteger(m.pp) || m.pp < 0 || m.pp > 128 || !Number.isInteger(m.ppUps) || m.ppUps < 0 || m.ppUps > 3) || new Set((value as Move[]).map(m => m.id)).size !== (value as Move[]).length)) { setError("Vérifie les identifiants des attaques, les doublons et les PP."); return; }
    if (field === "evs" && sum(value as Stats) > 510) { setError("Le total des EV ne peut pas dépasser 510."); return; }
    onEdit(p, { field, value }, baseline.fingerprint, `${p.name} · ${label} : ${JSON.stringify(baseline.values[field] ?? "—")} → ${JSON.stringify(value)}`);
  };
  const save = (field: string, label: string) => <button className={s.save} disabled={disabled || JSON.stringify(draft[field]) === JSON.stringify(baseline?.values[field])} onClick={() => apply(field, label)}>Préparer · {label}</button>;
  const field = (key: string, label: string, options?: { min?: number; max?: number; step?: number; choices?: string[]; hint?: string }) => <div className={s.field} key={key}><label>{label}{typeof draft[key] === "boolean" ? <select value={String(draft[key])} disabled={disabled} onChange={e => set(key, e.target.value === "true")}><option value="true">Oui</option><option value="false">Non</option></select> : options?.choices ? <select value={String(draft[key] ?? "")} disabled={disabled} onChange={e => set(key, e.target.value)}>{options.choices.map(v => <option key={v}>{v}</option>)}</select> : <input type={typeof draft[key] === "number" ? "number" : "text"} value={String(draft[key] ?? "")} min={options?.min} max={options?.max} step={options?.step ?? 1} maxLength={key === "nickname" ? 32 : 160} disabled={disabled} onChange={e => set(key, typeof draft[key] === "number" ? (e.target.value === "" ? NaN : Number(e.target.value)) : e.target.value)}/>}</label>{options?.hint && <small>{options.hint}</small>}{save(key, label)}</div>;
  const ivs = draft.ivs as Stats | undefined, evs = draft.evs as Stats | undefined;
  return <section className={s.detail} aria-label={`Fiche Pokémon ${p.name}`}>
    <header className={s.hero}><PokemonPortrait pokemon={p}/><div className={s.heroText}><span className={s.kicker}>{p.storage === "party" ? "ÉQUIPE" : "PC"} / {p.editor?.form ?? "FICHE SERVEUR"}</span><h3>{p.name} {p.shiny && <span title="Chromatique">✦</span>}</h3><p>{pretty(p.species)}</p><div className={s.types}>{p.editor?.types.map(t => <span key={t}>{types[t] ?? t}</span>)}</div></div><div className={s.level}><small>NIVEAU</small><strong>{p.level}</strong></div></header>
    {p.editor && <div className={s.health}><span>Points de vie</span><b>{String(p.editor.values.currentHealth)} / {p.editor.maxHealth}</b><progress aria-label="Points de vie" value={Number(p.editor.values.currentHealth)} max={p.editor.maxHealth || 1}/></div>}
    {!p.editor || !baseline ? <div className={s.message}><h4>Ancienne version de la passerelle</h4><p>Installe le nouveau JAR serveur pour lire les statistiques structurées et activer l’éditeur complet.</p><button disabled={!writable} onClick={() => onLegacy(p)}>Modifier le niveau</button></div> : <>
      {(!writable || !capable) && <p className={s.message}>Lecture seule : joueur hors ligne, droits insuffisants, passerelle ancienne ou intervention en cours.</p>}
      {stale && <div className={s.message} role="status">Le Pokémon a changé côté serveur. Ton brouillon est conservé, mais ne peut plus être envoyé.<button onClick={() => { setBaseline(p.editor); setDraft(structuredClone(p.editor!.values)); setError(""); }}>Recharger les valeurs du serveur</button></div>}
      <nav className={s.tabs} aria-label="Paramètres Pokémon">{["Statistiques", "Identité", "Attaques", "Avancé"].map(t => <button key={t} aria-pressed={tab === t} onClick={() => setTab(t)}>{t}</button>)}</nav>
      {error && <p role="alert" className={s.message}>{error}</p>}
      {tab === "Statistiques" && ivs && evs && <><div className={s.totals}><div><small>Potentiel naturel</small><b>{sum(ivs)} <span>/ 186 IV</span></b></div><div><small>Entraînement</small><b className={sum(evs) > 510 ? s.invalid : ""}>{sum(evs)} <span>/ 510 EV</span></b></div></div><p className={s.hint}>IV : 0–31 par stat. EV : 0–252 par stat, 510 au total. Les stats calculées affichées sont celles du dernier relevé.</p><div className={s.statScroll}><table className={s.stats}><thead><tr><th>Statistique</th><th>Valeur</th><th>IV</th><th>EV</th></tr></thead><tbody>{stats.map(([key, label]) => <tr key={key}><th>{label}<progress aria-label={`Entraînement ${label}`} value={evs[key]} max={252}/></th><td><b>{baseline.stats[key]}</b>{baseline.effectiveIvs[key] !== (baseline.values.ivs as Stats)[key] && <small title="IV effectif après entraînement ultime">IV effectif : {baseline.effectiveIvs[key]}</small>}</td>{(["ivs", "evs"] as const).map(group => <td key={group}><input aria-label={`${label} ${group === "ivs" ? "IV" : "EV"}`} type="number" min={0} max={group === "ivs" ? 31 : 252} value={Number.isNaN((draft[group] as Stats)[key]) ? "" : (draft[group] as Stats)[key]} disabled={disabled} onChange={e => set(group, { ...(draft[group] as Stats), [key]: e.target.value === "" ? NaN : Number(e.target.value) })}/></td>)}</tr>)}</tbody></table></div><div className={s.actions}>{save("ivs", "IV")}{save("evs", "EV")}</div><div className={s.fields}>{field("level", "Niveau", { min: 1, max: 100 })}{field("currentHealth", "PV actuels", { min: 0, max: baseline.maxHealth })}{field("friendship", "Bonheur", { min: 0, max: 255 })}</div><button className={s.heal} disabled={disabled} onClick={() => apply("heal", "Soin complet (PV, PP, statut)", true)}>Soigner complètement</button></>}
      {tab === "Identité" && <div className={s.fields}>{field("species", "Espèce", { hint: "Identifiant réel, ex. cobblemon:dragonite. Recalcule les caractéristiques de l’espèce." })}{field("nickname", "Surnom", { hint: "Vide = nom d’espèce. 32 caractères maximum." })}{field("shiny", "Chromatique")}{field("gender", "Sexe", { choices: ["MALE", "FEMALE", "GENDERLESS"] })}{field("nature", "Nature", { hint: "Identifiant Cobblemon, ex. cobblemon:adamant." })}{field("mintedNature", "Nature de menthe", { hint: "Vide pour retirer l’effet de la menthe." })}{field("ability", "Talent", { hint: "Identifiant réel, ex. innerfocus. Validé par le serveur." })}</div>}
      {tab === "Attaques" && <><p className={s.hint}>1 à 4 attaques distinctes. Utilise leur identifiant Cobblemon (ex. thunderbolt). Les PP maximums sont vérifiés par le serveur.</p><div className={s.moves}>{(draft.moves as Move[]).map((move, i) => <div className={s.move} key={i}><b>0{i + 1}</b><label>Attaque {i + 1}<input value={move.id} disabled={disabled} onChange={e => set("moves", (draft.moves as Move[]).map((m, j) => j === i ? { ...m, id: e.target.value } : m))}/></label><label>PP<input type="number" value={move.pp} min={0} max={128} disabled={disabled} onChange={e => set("moves", (draft.moves as Move[]).map((m, j) => j === i ? { ...m, pp: Number(e.target.value) } : m))}/></label><label>PP Plus<input type="number" value={move.ppUps} min={0} max={3} disabled={disabled} onChange={e => set("moves", (draft.moves as Move[]).map((m, j) => j === i ? { ...m, ppUps: Number(e.target.value) } : m))}/></label><button aria-label={`Retirer attaque ${i + 1}`} disabled={disabled || (draft.moves as Move[]).length === 1} onClick={() => set("moves", (draft.moves as Move[]).filter((_, j) => j !== i))}>×</button></div>)}</div><div className={s.actions}><button disabled={disabled || (draft.moves as Move[]).length >= 4} onClick={() => set("moves", [...draft.moves as Move[], { id: "", pp: 1, ppUps: 0 }])}>+ Ajouter une attaque</button>{save("moves", "Attaques")}</div></>}
      {tab === "Avancé" && <><details className={s.raw}><summary>Entraînement ultime · IV effectifs</summary><p>-1 = aucun entraînement ultime. Sinon, IV effectif de 0 à 31 (sans changer les IV héritables).</p><div className={s.fields}>{stats.map(([key, label]) => <label key={key}>{label}<input type="number" min={-1} max={31} disabled={disabled} value={(draft.hyperIvs as Stats)?.[key] ?? -1} onChange={e => set("hyperIvs", { ...(draft.hyperIvs as Stats), [key]: Number(e.target.value) })}/></label>)}</div>{save("hyperIvs", "Entraînement ultime")}</details><p className={s.hint}>Les identifiants doivent exister sur le serveur. Remplacer l’objet tenu retire l’ancien objet ; il n’est pas donné au joueur.</p><div className={s.fields}>{field("experience", "Expérience Pokémon", { min: 0, max: 2_000_000, hint: "Recalcule le niveau. Limite réelle selon la courbe de l’espèce." })}{field("status", "Altération de statut", { hint: "Identifiant serveur, ex. cobblemon:paralysis. Vide = retirer." })}{field("heldItem", "Objet tenu", { hint: "Ex. minecraft:diamond. Vide = retirer." })}{field("caughtBall", "Ball de capture", { hint: "Ex. cobblemon:poke_ball." })}{field("teraType", "Type Téracristal", { hint: "Ex. cobblemon:dragon." })}{field("scale", "Échelle visuelle", { min: .1, max: 3, step: .05 })}{field("dmaxLevel", "Niveau Dynamax", { min: 0, max: 10 })}{field("gmaxFactor", "Facteur Gigamax")}{field("tradeable", "Échange autorisé")}</div><p className={s.hint}>UUID, propriétaire et données internes de stockage ne sont pas modifiables ici. Les propriétés spécifiques aux autres mods restent consultables dans la sauvegarde.</p></>}
    </>}
    <p className={s.hint}>Illustrations Pokémon via <a href="https://github.com/PokeAPI/sprites" target="_blank" rel="noreferrer">PokéAPI</a> : ce ne sont pas des captures des modèles 3D Cobblemon.</p><details className={s.raw}><summary>Sauvegarde brute · UUID et propriétés techniques</summary><code>{p.uuid}</code><pre>{JSON.stringify(p.data, null, 2)}</pre></details>
  </section>;
}
