"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { ChoiceField, NumberField } from "./Fields";
import { TeamEditor, TeamPortrait } from "./TeamEditor";
import { RewardEditor } from "./RewardEditor";
import { TrainerEditor } from "./TrainerEditor";
import { TrialEditor } from "./TrialEditor";
import { CaptainSignature } from "./CaptainSignature";
import { THEME, captainTeamPatch, hydrateAdventure, validate, type ArenaContent, type ArenaStage, type ArenaState, type Server } from "./model";
import s from "./arenas.module.css";

type Tab = "champion" | "team" | "rewards" | "trainers" | "trial";
class ApiError extends Error { constructor(message: string, public status: number) { super(message); } }
async function api<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, { credentials: "include", cache: "no-store", ...init, headers: { "Content-Type": "application/json", ...init?.headers } });
  const body = await response.json().catch(() => null);
  if (!response.ok) throw new ApiError(response.status === 401 ? "Connecte-toi avec ton compte Discord administrateur." : response.status === 403 ? "Ce compte n’a pas les droits d’accès aux épreuves." : response.status === 409 ? "Le brouillon a été modifié ailleurs. Tes modifications locales sont conservées : compare les versions avant de recharger." : body?.message ?? "Le serveur ne répond pas. Aucun changement n’a été envoyé en jeu.", response.status);
  return body as T;
}
const timestamp = (value: string | null) => value ? new Date(value).toLocaleString("fr-FR", { dateStyle: "short", timeStyle: "short" }) : "Pas encore synchronisé";

export default function ArenaStudio() {
  const [servers, setServers] = useState<Server[]>([]), [server, setServer] = useState("");
  const [state, setState] = useState<ArenaState | null>(null), [content, setContent] = useState<ArenaContent | null>(null);
  const [selected, setSelected] = useState(""), [tab, setTab] = useState<Tab>("champion"), [query, setQuery] = useState("");
  const [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [dirty, setDirty] = useState(false), [conflict, setConflict] = useState(false);
  const [message, setMessage] = useState(""), [error, setError] = useState(""), [problems, setProblems] = useState<string[]>([]);
  const [reason, setReason] = useState(""), [publishOpen, setPublishOpen] = useState(false), [now, setNow] = useState(0);
  const [undo, setUndo] = useState<ArenaContent[]>([]), [redo, setRedo] = useState<ArenaContent[]>([]);
  const dirtyRef = useRef(false), revisionRef = useRef(0), requestId = useRef(0);
  const dialog = useRef<HTMLDialogElement>(null), publishButton = useRef<HTMLButtonElement>(null);
  const endpoint = (id: string) => `/api/admin/arenas/${encodeURIComponent(id)}`;
  const absorb = useCallback((result: ArenaState, replace: boolean) => {
    setNow(Date.now());
    if (replace) { const next = hydrateAdventure(structuredClone(result.content), result.observed); const migrated = JSON.stringify(next) !== JSON.stringify(result.content); setState(result); setContent(next); setDirty(migrated); dirtyRef.current = migrated; setConflict(false); revisionRef.current = result.draftRevision; setUndo([]); setRedo([]); setProblems([]); }
    else { setState(old => old ? { ...result, content: old.content, draftRevision: old.draftRevision } : result); if (result.draftRevision !== revisionRef.current) setConflict(true); }
  }, []);
  const load = useCallback(async (id: string, replace: boolean) => { const token = ++requestId.current; const result = await api<ArenaState>(`/api/admin/arenas/${encodeURIComponent(id)}`); if (token !== requestId.current) return; absorb(result, replace); }, [absorb]);
  const invalidateRequests = useCallback(() => { requestId.current++; }, []);
  useEffect(() => { let active = true; void api<{ servers: Server[]; canWrite: boolean }>("/api/admin/arenas").then(async result => { if (!active) return; setServers(result.servers); if (result.servers[0]) { setServer(result.servers[0].serverId); await load(result.servers[0].serverId, true); } }).catch(e => { if (active) setError((e as Error).message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; invalidateRequests(); }; }, [load, invalidateRequests]);
  useEffect(() => {
    if (!server) return;
    let active = true;
    const timer = window.setInterval(() => { setNow(Date.now()); void api<ArenaState>(endpoint(server)).then(result => { if (active) absorb(result, !dirtyRef.current && result.draftRevision === revisionRef.current); }).catch(() => { if (active) setError("Actualisation automatique indisponible. Le brouillon local est conservé."); }); }, 15000);
    return () => { active = false; window.clearInterval(timer); };
  }, [server, absorb]);
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (dirty) e.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  useEffect(() => { if (publishOpen) dialog.current?.showModal(); else if (dialog.current?.open) { dialog.current.close(); publishButton.current?.focus(); } }, [publishOpen]);
  const writable = !!state?.canWrite;
  const hasUnpublishedChanges = state?.hasUnpublishedChanges ?? (state?.draftRevision !== state?.publishedRevision);
  const stage = content?.stages.find(a => a.id === selected) ?? content?.stages[0];
  const fresh = !!state?.lastSeenAt && now - new Date(state.lastSeenAt).getTime() < 90000;
  const syncLabel = !fresh ? "Serveur à reconnecter" : state?.error ? "Application refusée" : state?.publishedRevision === 0 ? "Configuration serveur importée" : state?.appliedRevision === state?.publishedRevision ? "Appliqué en jeu" : "En attente du serveur";
  function commit(next: ArenaContent) { if (!writable || busy) return; setUndo(values => [...values.slice(-19), structuredClone(content!)]); setRedo([]); setContent(next); setDirty(true); dirtyRef.current = true; setProblems([]); setMessage(""); }
  function patch(patch: Partial<ArenaStage>) { if (content && stage) commit({ ...content, stages: content.stages.map(a => a.id === stage.id ? { ...a, ...patch } : a) }); }
  async function task(fn: () => Promise<void>) { setBusy(true); setError(""); try { await fn(); } catch (e) { setError((e as Error).message); if (e instanceof ApiError && e.status === 409) setConflict(true); if (e instanceof ApiError && (e.status === 401 || e.status === 403)) setState(old => old ? { ...old, canWrite: false } : old); } finally { setBusy(false); } }
  async function save() {
    if (!content || !state || !writable) return;
    const errors = validate(content, state.catalog); setProblems(errors); if (errors.length) { setError("Quelques réglages sont à corriger avant l’enregistrement."); return; }
    const response = await api<{ draftRevision: number }>(endpoint(server), { method: "PUT", body: JSON.stringify({ baseRevision: revisionRef.current, content }) });
    revisionRef.current = response.draftRevision; setState(old => old ? { ...old, content: structuredClone(content), draftRevision: response.draftRevision, hasUnpublishedChanges: true } : old); setDirty(false); dirtyRef.current = false; setConflict(false); setMessage("Brouillon enregistré. Rien n’a encore changé en jeu.");
  }
  async function publish() {
    if (!state || !content || dirty || conflict || !writable || reason.trim().length < 3 || reason.trim().length > 300) return;
    const result = await api<{ publishedRevision: number }>(`${endpoint(server)}/publish`, { method: "POST", body: JSON.stringify({ baseRevision: revisionRef.current, reason: reason.trim() }) });
    setState(old => old ? { ...old, publishedRevision: result.publishedRevision, hasUnpublishedChanges: false } : old); setPublishOpen(false); setReason(""); setMessage(`Version ${result.publishedRevision} publiée. En attente de confirmation du serveur ; une publication n’est pas encore une application en jeu.`);
  }
  return <main className={s.page} id="contenu"><div className={s.container}>
    <header className={s.header}><Link href="/admin/" className={s.brand}><img src="/cobblestar-logo.png" alt="Mascotte Dracolosse CobbleStar" width={64} height={64}/><span><b>COBBLESTAR</b><small>ATELIER DES ÉPREUVES</small></span></Link><nav aria-label="Administration"><Link href="/admin/">Centre de contrôle</Link><Link href="/admin/creation/">Quêtes & PNJ</Link><Link href="/admin/joueurs/">Joueurs</Link></nav></header>
    <section className={s.hero}><div><span className={s.eyebrow}>LES RENCONTRES QUI MARQUENT L’AVENTURE</span><h1>Huit épreuves.<br/><em>Une grande ascension.</em></h1><p>Énigmes, dresseurs, Pokémon Totems et Capitaines : prépare un parcours unique jusqu’aux portes de la Ligue.</p></div><div className={s.heroSteps}><span><b>01</b> Compose</span><span><b>02</b> Enregistre</span><span><b>03</b> Publie en jeu</span></div></section>
    {error && <div className={s.error} role="alert"><b>{error}</b>{!state && <p><Link href="/compte/">Ouvrir mon compte</Link> · <button type="button" onClick={() => location.reload()}>Réessayer</button></p>}</div>}
    {message && <p className={s.notice} role="status">{message}</p>}
    {loading && <section className={s.empty} aria-live="polite"><span className={s.loadingStar}>✦</span><h2>Lecture des épreuves du serveur…</h2><p>Aucune configuration fictive n’est affichée.</p></section>}
    {!loading && !servers.length && !error && <section className={s.empty}><span>✦</span><h2>Le serveur n’a pas encore partagé ses épreuves.</h2><p>Installe le nouveau JAR CobbleStar, active la passerelle admin puis connecte le serveur. Les épreuves et les vrais catalogues apparaîtront ici.</p><button onClick={() => location.reload()}>Actualiser</button></section>}
    {state && content && <><section className={s.toolbar} aria-label="Publication et synchronisation"><label>Serveur<select aria-label="Serveur" value={server} disabled={busy} onChange={e => { if (dirty && !confirm("Changer de serveur et abandonner les modifications non enregistrées ?")) return; const id = e.target.value; setServer(id); setSelected(""); void task(() => load(id, true)); }}>{servers.map(x => <option value={x.serverId} key={x.serverId}>{x.serverId}</option>)}</select></label><div className={s.sync}><b data-tone={state.error ? "error" : fresh ? "ready" : "pending"}>{syncLabel}</b><small>Brouillon {state.draftRevision} · publié {state.publishedRevision} · appliqué {state.appliedRevision}</small><small>Dernier contact : {timestamp(state.lastSeenAt)}</small></div><div className={s.toolbarActions}><button disabled={busy} onClick={() => void task(async () => { await load(server, false); setMessage(dirty ? "Statut actualisé. Tes modifications locales sont conservées." : "Statut actualisé."); })}>Actualiser le statut</button>{writable && <><button disabled={busy || !dirty || conflict} onClick={() => void task(save)}>Enregistrer{dirty ? " *" : ""}</button><button ref={publishButton} className={s.primary} disabled={busy || dirty || conflict || !state.draftRevision || !hasUnpublishedChanges} onClick={() => setPublishOpen(true)}>Publier en jeu ↗</button></>}</div></section>
      {state.runtime && <>
        {state.runtime.pendingRewards > 0 && <section className={s.notice} role="status"><b>{state.runtime.pendingRewards.toLocaleString("fr-FR")} récompense(s) en attente de livraison</b><p>Ces bonus sont enregistrés par le serveur et n’ont pas encore été distribués. Ne les recrée pas manuellement pour éviter une double récompense.</p>{!fresh && <small>Dernier état reçu le {timestamp(state.lastSeenAt)} ; reconnecte le serveur pour connaître la situation actuelle.</small>}</section>}
        {state.runtime.reviewRewards > 0 && <section className={s.error} role="alert"><b>{state.runtime.reviewRewards.toLocaleString("fr-FR")} livraison(s) à contrôler</b><p>Le serveur ne peut pas confirmer leur livraison de façon sûre. Vérifie les récompenses des joueurs concernés avant toute nouvelle attribution : aucune redistribution automatique ne doit être présumée.</p>{!fresh && <small>Dernier état reçu le {timestamp(state.lastSeenAt)} ; ces données peuvent avoir changé depuis.</small>}</section>}
        {!state.runtime.worldReady && <p className={s.notice}>La zone de combat n’est pas encore prête. Tu peux préparer et enregistrer la configuration, mais ce statut ne signifie pas que les épreuves sont déjà jouables.</p>}
        {state.runtime.activeBattles > 0 && <p className={s.notice}>{state.runtime.activeBattles.toLocaleString("fr-FR")} combat(s) ou session(s) d’épreuve en cours{!fresh ? " lors du dernier contact" : ""}. Une publication attendra la fin des sessions avant de remplacer les PNJ.</p>}
      </>}
      {!writable && <p className={s.notice}>Mode lecture seule : tes droits permettent de consulter les épreuves, pas de les modifier.</p>}
      {content.schemaVersion === 1 && <p className={s.notice}>Ancien catalogue encore synchronisé. Installe le nouveau JAR puis actualise : le Conseil passera à Spectre → Dragon → Fée → Acier → Maître, sans écraser tes équipes existantes.</p>}
      {content.schemaVersion === 2 && state.content.schemaVersion === 1 && <p className={s.notice}>Migration préparée dans ton brouillon : Spectre, Dragon et Maître gardent leurs équipes ; Fée et Acier restent à configurer. Enregistre puis publie pour valider ce nouvel ordre.</p>}
      {!!content.legacyLeagueStages?.length && <details className={s.notice}><summary>Archives des anciens Conseils — {content.legacyLeagueStages.length} rencontres conservées, hors du parcours</summary>{content.legacyLeagueStages.map(old => <p key={old.id}><b>{old.name} · {old.champion}</b><br/>{old.team.map(p => p.species + " N. " + p.level).join(" · ")}<br/><small>Équipes et récompenses conservées dans le catalogue, sans réattribution de victoires.</small></p>)}</details>}
      {content.stages.some(a => a.trial && !state.content.stages.find(old => old.id === a.id)?.trial) && <p className={s.notice}>Les parcours reçus du nouveau mod ont été ajoutés à ta copie locale. Tes champions, équipes et bonus sont conservés. Enregistre puis publie pour intégrer ces nouvelles épreuves au brouillon du site.</p>}
      {state.error && <p role="alert" className={s.error}>Le serveur a refusé la dernière application : {state.error}</p>}
      {conflict && <section className={s.conflict} role="alert"><h3>Une autre version existe.</h3><p>Rien n’a écrasé ton travail. La sauvegarde et la publication sont suspendues pour éviter d’effacer les modifications d’un autre administrateur.</p><details><summary>Comparer avec le brouillon actuel du site</summary><button disabled={busy} onClick={() => void task(async () => { const remote = await api<ArenaState>(endpoint(server)); setMessage(`Brouillon distant ${remote.draftRevision} : ${remote.content.stages.map(a => `${a.name} — ${a.champion}, ${a.team.length} Pokémon, ${a.trainers.length} dresseur(s)`).join(" ; ")}`); })}>Lire le résumé de la version distante</button></details><button disabled={busy} onClick={() => { if (!dirty || confirm("Recharger le brouillon du site ? Les modifications locales non enregistrées seront abandonnées.")) void task(async () => { await load(server, true); setMessage("Brouillon du site rechargé."); }); }}>Recharger la version du site</button></section>}
      {problems.length > 0 && <section className={s.error} role="alert"><b>{problems.length} point(s) à corriger</b><ul>{problems.slice(0, 20).map((p, i) => <li key={i}>{p}</li>)}</ul></section>}
      <div className={s.workspace}><aside className={s.directory}><header><span className={s.eyebrow}>LE PARCOURS</span><h2>Épreuves & Ligue</h2></header><input type="search" aria-label="Rechercher une épreuve" placeholder="Épreuve, type, champion…" value={query} onChange={e => setQuery(e.target.value)}/>{[false, true].map(league => <section key={String(league)}><h3>{league ? "LE CONSEIL & LE MAÎTRE" : "LA ROUTE DES 8 BADGES"}</h3>{content.stages.filter(a => a.league === league && `${a.name} ${a.champion} ${THEME[a.theme] ?? a.theme}`.toLocaleLowerCase("fr").includes(query.toLocaleLowerCase("fr"))).map(a => <button key={a.id} type="button" className={s.stageButton} aria-pressed={stage?.id === a.id} onClick={() => { setSelected(a.id); setTab("champion"); }}><span className={s.stageNumber}>{a.league ? a.id === "champion" ? "✦" : a.index - 8 : String(a.index).padStart(2, "0")}</span><span><b>{a.league ? a.name : THEME[a.theme] ?? a.name}</b><small>{a.champion} · {a.team.length} Pokémon</small></span><span aria-hidden="true">›</span></button>)}</section>)}<p>Les badges et l’ordre du parcours restent gérés par CobbleStar.</p></aside>
      {stage ? <article className={s.editor}><header className={s.stageHeading}><div><span className={s.eyebrow}>{stage.league ? "LIGUE COBBLESTAR" : `ÉPREUVE ${String(stage.index).padStart(2, "0")} · ${THEME[stage.theme]?.toUpperCase()}`}</span><h2>{stage.name}</h2><p>{stage.champion} · {stage.team.length} Pokémon · {stage.trainers.filter(t => t.enabled).length} dresseur(s)</p></div>{stage.team[0] && <div className={s.stagePortrait}><TeamPortrait pokemon={stage.team[0]} catalog={state.catalog}/></div>}</header>
        <nav className={s.tabs} aria-label="Réglages de l’épreuve">{([['champion', 'Capitaine'], ['team', 'Équipe'], ['rewards', 'Récompenses'], ['trainers', 'Dresseurs'], ['trial', 'Parcours']] as const).map(([id, title], i) => <button type="button" key={id} aria-pressed={tab === id} onClick={() => setTab(id)}><span>{i + 1}</span>{title}{id === "trainers" && <small>{stage.trainers.length}</small>}</button>)}</nav>
        <fieldset disabled={!writable || busy} className={s.editorFields} key={`${stage.id}:${tab}`}><legend className={s.srOnly}>Configuration de {stage.name}</legend>
        {tab === "champion" && <section><div className={s.sectionHeading}><div><h3>Le visage de cette épreuve.</h3><p>Le nom, le modèle et le comportement de combat du Capitaine présent dans le jeu.</p></div></div><div className={s.grid}><label>Nom du Capitaine<input maxLength={64} value={stage.champion} onChange={e => patch({ champion: e.target.value })}/></label><label>Nom de l’épreuve<input maxLength={80} value={stage.name} onChange={e => patch({ name: e.target.value })}/></label><ChoiceField label="Modèle du Capitaine" choices={state.catalog?.npcClasses} value={stage.npcClass} onChange={npcClass => patch({ npcClass })}/><NumberField label="Stratégie du Capitaine" max={100} value={stage.skill} onChange={skill => patch({ skill })}/><NumberField label="Niveau conseillé de l’épreuve" min={1} max={100} value={stage.level} onChange={level => patch({ level })}/><div className={s.hint}><b>Une stratégie, pas une statistique cachée</b><small>De 0 à 100 : influence les décisions du PNJ. Les niveaux, IV et EV se règlent séparément dans son équipe.</small></div></div><div className={s.nextCard}><span>À préparer ensuite</span><h4>Son équipe fait toute la différence.</h4><p>Choisis ses Pokémon, attaques, talents, objets et statistiques pour créer un combat reconnaissable.</p><button type="button" onClick={() => setTab("team")}>Composer son équipe →</button></div></section>}
        {tab === "team" && <><CaptainSignature stage={stage} catalog={state.catalog} onChange={patch}/><TeamEditor serverId={server} team={stage.team} catalog={state.catalog} level={stage.level} onChange={team => patch(captainTeamPatch(stage, team))}/></>}
        {tab === "rewards" && <RewardEditor champion league={stage.league} rewards={stage.rewards} catalog={state.catalog} onChange={rewards => patch({ rewards })}/>}
        {tab === "trainers" && <TrainerEditor stage={stage} catalog={state.catalog} serverId={server} onChange={trainers => patch({ trainers })}/>}
        {tab === "trial" && <TrialEditor stage={stage} content={content} catalog={state.catalog} onChange={trial => patch({ trial })} showTrainers={() => setTab("trainers")}/>}
        </fieldset><footer className={s.editorFooter}><span>{dirty ? "● Modifications non enregistrées" : "Brouillon enregistré"}</span>{writable && <div className={s.inlineActions}><button disabled={busy || !undo.length} onClick={() => { setRedo(v => [...v, structuredClone(content)]); setContent(undo[undo.length - 1]); setUndo(v => v.slice(0, -1)); setDirty(true); dirtyRef.current = true; }}>↶ Annuler</button><button disabled={busy || !redo.length} onClick={() => { setUndo(v => [...v, structuredClone(content)]); setContent(redo[redo.length - 1]); setRedo(v => v.slice(0, -1)); setDirty(true); dirtyRef.current = true; }}>↷ Rétablir</button></div>}</footer></article> : <section className={s.empty}><h2>Aucune épreuve reçue.</h2><p>La configuration sera disponible après la prochaine synchronisation du serveur.</p></section>}</div>
      <section className={s.audit}><div><span className={s.eyebrow}>UNE PUBLICATION TRAÇABLE</span><h2>Du brouillon au terrain.</h2><p>Enregistrer ne change pas le jeu. Publier envoie une version complète au serveur, qui la valide avant application. Les combats déjà commencés doivent se terminer avant le changement des PNJ.</p></div><div><h3>Dernières publications</h3>{state.history.length ? state.history.slice(0, 5).map(h => <article key={h.revision}><b>Version {h.revision}</b><p>{h.reason}</p><small>{h.actor} · {timestamp(h.createdAt)}</small></article>) : <p>Aucune publication depuis cet atelier.</p>}</div></section>
    </>}
    <dialog ref={dialog} className={s.publishDialog} onCancel={e => { if (busy) e.preventDefault(); else setPublishOpen(false); }} onClose={() => setPublishOpen(false)}><form onSubmit={e => { e.preventDefault(); void task(publish); }}><span className={s.eyebrow}>PUBLICATION EN JEU</span><h2>Prêt pour les dresseurs ?</h2><p>Tu vas publier le brouillon {state?.draftRevision} sur <b>{server}</b>. Champions, équipes, récompenses et dresseurs seront mis à jour après validation par le serveur.</p><label>Motif de publication<textarea autoFocus maxLength={300} minLength={3} required value={reason} onChange={e => setReason(e.target.value)} placeholder="Ex. Équilibrage d’Eau et ajout des deux dresseurs d’entraînement"/></label>{error && <p role="alert" className={s.error}>{error}</p>}<div className={s.inlineActions}><button type="button" disabled={busy} onClick={() => setPublishOpen(false)}>Revenir au brouillon</button><button type="submit" className={s.primary} disabled={busy || reason.trim().length < 3 || reason.trim().length > 300 || dirty || conflict}>{busy ? "Publication…" : "Confirmer la publication"}</button></div></form></dialog>
  </div></main>;
}
