"use client";

import { useState } from "react";
import { ChoiceField, NumberField } from "./Fields";
import { blankRewards, newPokemon, SLOT_LABELS, type ArenaStage, type Catalog, type TrainerSpec } from "./model";
import { TeamEditor, TeamPortrait } from "./TeamEditor";
import { RewardEditor } from "./RewardEditor";
import s from "./arenas.module.css";

export function TrainerEditor({ stage, catalog, onChange }: { stage: ArenaStage; catalog: Catalog | null; onChange: (trainers: TrainerSpec[]) => void }) {
  const [selected, setSelected] = useState(""), [tab, setTab] = useState<"identity" | "team" | "rewards">("identity");
  const trainer = stage.trainers.find(t => t.id === selected) ?? stage.trainers[0];
  const adventure = !stage.league && !!stage.trial;
  const patch = (value: Partial<TrainerSpec>) => onChange(stage.trainers.map(t => t.id === trainer.id ? { ...t, ...value } : t));
  const freeSlot = Array.from({ length: 6 }, (_, i) => i).find(slot => !stage.trainers.some(t => t.slot === slot));
  return <section><div className={s.sectionHeading}><div><h3>Le chemin vers le champion.</h3><p>{adventure ? "Prépare jusqu’à six rencontres dans le parcours. Chaque dresseur présent doit être vaincu avant le Totem et le champion." : "Prépare jusqu’à six dresseurs. Ceux marqués obligatoires doivent être battus avant le champion."}</p></div><span className={s.pill}>{stage.trainers.length} / 6</span></div>
    <div className={s.trainerOverview}><div className={s.floorPlan} aria-label="Emplacements prédéfinis des dresseurs"><span className={s.floorChampion}>LES RENCONTRES DU PARCOURS</span><div>{[0, 1, 2, 3, 4, 5].map(slot => { const occupant = stage.trainers.find(t => t.slot === slot); return <button type="button" key={slot} disabled={!occupant} aria-pressed={!!occupant && occupant.id === trainer?.id} onClick={() => occupant && setSelected(occupant.id)}><b>{occupant?.name ?? "Libre"}</b><small>{SLOT_LABELS[slot]}</small>{occupant && <small>{!occupant.enabled ? "Masqué" : occupant.required ? "Obligatoire" : "Facultatif"}</small>}</button>; })}</div><small>{adventure ? "PUIS LE TOTEM ET LE CHAMPION" : "RENCONTRES CONFIGURÉES"}</small></div><div className={s.trainerSummary}><h4>Un parcours clair</h4><p><b>{stage.trainers.filter(t => t.enabled && t.required).length}</b> duel(s) obligatoire(s){!adventure && <><br/><b>{stage.trainers.filter(t => t.enabled && !t.required).length}</b> rencontre(s) facultative(s)</>}</p><small>Emplacements fonctionnels, pas une vue du bâtiment. Les positions sont propres à chaque arène et définies par son parcours natif.</small><button type="button" disabled={freeSlot === undefined || !catalog?.species.length} onClick={() => { const next: TrainerSpec = { id: `trainer_${crypto.randomUUID().replaceAll("-", "").slice(0, 12)}`, name: "Nouveau dresseur", enabled: true, required: adventure, slot: freeSlot!, npcClass: stage.npcClass, skill: 50, team: [newPokemon(catalog!.species[0].id, Math.max(1, stage.level - 5))], rewards: blankRewards() }; onChange([...stage.trainers, next]); setSelected(next.id); setTab("identity"); }}>＋ Ajouter un dresseur</button></div></div>
    {trainer ? <div className={s.trainerDetail}><div className={s.trainerSwitch}>{stage.trainers.map(t => <button type="button" key={t.id} aria-pressed={trainer.id === t.id} onClick={() => setSelected(t.id)}>{t.team[0] && <TeamPortrait pokemon={t.team[0]} catalog={catalog}/>}<span><b>{t.name}</b><small>{SLOT_LABELS[t.slot]}</small></span></button>)}</div><nav className={s.subtabs} aria-label="Réglages du dresseur">{([['identity', 'Identité & place'], ['team', 'Son équipe'], ['rewards', 'Ses récompenses']] as const).map(([id, name]) => <button type="button" key={id} aria-pressed={tab === id} onClick={() => setTab(id)}>{name}</button>)}</nav>
      {tab === "identity" && <><div className={s.grid}><label>Nom du dresseur<input maxLength={64} value={trainer.name} onChange={e => patch({ name: e.target.value })}/></label><label>Emplacement du dresseur<select aria-label="Emplacement du dresseur" value={trainer.slot} onChange={e => patch({ slot: Number(e.target.value) })}>{SLOT_LABELS.map((name, slot) => <option key={slot} value={slot} disabled={stage.trainers.some(t => t.id !== trainer.id && t.slot === slot)}>{name}{stage.trainers.some(t => t.id !== trainer.id && t.slot === slot) ? " · occupé" : ""}</option>)}</select></label><ChoiceField label="Modèle du dresseur" choices={catalog?.npcClasses} value={trainer.npcClass} onChange={npcClass => patch({ npcClass })}/><NumberField label="Stratégie du dresseur" max={100} value={trainer.skill} onChange={skill => patch({ skill })}/></div><div className={s.checks}><label className={s.checkbox}><input type="checkbox" checked={trainer.enabled} onChange={e => patch({ enabled: e.target.checked, required: e.target.checked && (adventure || trainer.required) })}/>Présent dans l’arène</label>{!adventure && <label className={s.checkbox}><input type="checkbox" checked={trainer.required} disabled={!trainer.enabled} onChange={e => patch({ required: e.target.checked })}/>Victoire obligatoire avant le champion</label>}</div><p className={s.hint}>{adventure ? "Chaque dresseur présent fait partie de l’épreuve obligatoire. Tu peux masquer une rencontre, mais au moins un dresseur doit rester présent." : "Masquer un dresseur conserve son équipe et ses réglages. Un dresseur masqué ne bloque pas le champion."}</p><button type="button" className={s.danger} onClick={() => { if (confirm(`Retirer ${trainer.name} du brouillon ? Ses réglages seront supprimés lors de la publication.`)) { onChange(stage.trainers.filter(t => t.id !== trainer.id)); setSelected(""); } }}>Supprimer ce dresseur</button></>}
      {tab === "team" && <TeamEditor key={trainer.id} team={trainer.team} level={Math.max(1, stage.level - 5)} catalog={catalog} onChange={team => patch({ team })}/>}
      {tab === "rewards" && <RewardEditor rewards={trainer.rewards} catalog={catalog} onChange={rewards => patch({ rewards })}/>}
    </div> : <div className={s.emptySmall}><h4>Le champion n’a pas encore d’escorte.</h4><p>Ajoute un premier dresseur pour composer le parcours de cette arène.</p></div>}
  </section>;
}
